### ISSUE TITLE
Path de los CSS y funcion JS cambiarTheme

### ISSUE THREAD

**Issue by rferromoreno** [unsiaw/proyecto2#22]
Hay un temita con los paths relativos y la funcion al cambiar el css.

Cuando estamos en una ruta que no sea la raiz, y se quiere cambiar el theme, Laravel entiende que estamos tratando de buscar la ruta relativa.

por ejemplo si estoy en **/admin/autos/create** y hago click en cambiar theme va a ir a buscar el css a:
**/admin/autos/css/bootstrap.min.js**

Queda para más adelante ver como arreglar esto. En principio solucioné lo mismo a nivel JS usando URL::to(), pero esto de los themes no se puede solucionar igual, sino que de otra forma.

**Comment by matiaschap** [comment]
https://github.com/igaster/laravel-theme
